### ISSUE TITLE
マイページ機能の実装

### ISSUE THREAD

**Issue by yuckeyee** [yuki0204/twitter_clone#2]
# やること
メールアドレス、パスワードを変更できるようにする。また、名前とプロフィールもマイページにて登録できるようにする。画像アップロードにはActiveStorageを使用する予定。
- [ ] マイページの作成
- [ ] ユーザ名の追加
- [ ] 画像アップローダを実装する

# 参考イメージ
<img width="1233" alt="2018-05-21 20 08 09" src="https://user-images.githubusercontent.com/18512510/40304713-ba4e210c-5d32-11e8-8bd1-2a6b92be73cb.png">

**Comment by gotchane** [comment]
paperclipは開発終わっちゃうみたいだから、使わない方が良さそう。
代替としてActiveStorageとかがあるみたい。

https://robots.thoughtbot.com/closing-the-trombone
https://techracho.bpsinc.jp/hachi8833/2018_05_21/56668
